Update publish script
Signed-off-by: Erin Allison <erin@eallison.us>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -6,8 +6,6 @@ on:
 jobs:
   upload-key:
     runs-on: ubuntu-latest
-    container:
-      image: archlinux:base-devel
     steps:
       - name: Import signing key
         uses: crazy-max/ghaction-import-gpg@v4
@@ -28,86 +26,96 @@ jobs:
       - name: Set up build user
         run: |
           echo "build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build
-          useradd build -u 1000
-          mkdir -p /home/build/.config/crema
-          echo -e "[ea-private]\nRemotePath = \"/home/build/ea-private/\"\nSignDB = false" > /home/build/.config/crema/repos.conf
-          mkdir /home/build/ea-private/ /home/build/source
-          cp -r ./* /home/build/source/
-          chown -R build: /home/build
-          echo 'MAKEFLAGS="-j2"' >> /etc/makepkg.conf
+          useradd build -m -d /home/build
 
       - name: Install dependencies
         run: |
-          pacman -Syu --needed --noconfirm git go nano asciidoctor rsync
+          cat << EOF >> /etc/pacman.conf
+
+          [multilib]
+          Include = /etc/pacman.d/mirrorlist
+          EOF
+
+          pacman -Syu --needed --noconfirm --noprogressbar git
+
+          sudo -u build bash << EOF
+          cd /home/build
+          git clone https://aur.archlinux.org/paru-bin.git
+          cd paru-bin
+          makepkg -si --noconfirm --noprogressbar
+
+          paru -Syu --noconfirm --noprogressbar aurutils
+          EOF
+
+      - name: Set up build environment
+        run: |
+          mkdir /home/build/repo/ /home/build/source
+          repo-add /home/build/repo/ea-private.db.tar.gz
+          cp -r ./* /home/build/source/
+          chown -R build: /home/build
+          echo 'MAKEFLAGS="-j2"' >> /etc/makepkg.conf
+          cat << EOF >> /etc/pacman.conf
+
+          [ea-private]
+          SigLevel = Optional TrustAll
+          Server = file:///home/build/repo
+          EOF
 
       - name: Load GPG public keys
         run: |
           sudo -u build gpg --recv-keys 6AD860EED4598027 # Tony Hutter (GPG key for signing ZFS releases) <hutter2@llnl.gov>
           sudo -u build gpg --recv-keys 0AB9E991C6AF658B # Brian Behlendorf <behlendorf1@llnl.gov>
-
-      - name: Set up crema
-        run: |
-          pushd /tmp > /dev/null
-          curl https://gitlab.com/mipimipi/crema/-/archive/v2.7.5/crema-v2.7.5.tar | tar -x
-          cd crema-v2.7.5
-          make
-          make install
-          popd > /dev/null
-          rm -rf crema-v2.7.5
+          sudo -u build gpg --recv-keys 7373B12CE03BEB4B # RuneScape Linux <noreply@jagex.com>
 
       - name: Run initial build
         run: |
-          packages=`find /home/build/source/ -name PKGBUILD -exec dirname {} \;`
-          crema="crema add -r ea-private -n"
-          for package in $packages
-          do
-            echo "::group::Building local package \"$(basename $package)\""
-            sudo -u build $crema -l $package
-            echo "::endgroup::"
-          done
+          sudo -u build bash << EOF
+          cd /home/build
+
+          find source -name PKGBUILD -exec dirname {} \; | \
+          aur build -s --noconfirm -a /dev/stdin
+          EOF
 
       - name: Add additional dependencies
         run: |
-
-          echo -e "\n[ea-private]\nSigLevel = Optional TrustAll\nServer = file:///home/build/ea-private/\n" >> /etc/pacman.conf
+          pacman -Sy
 
           i=0
           while true
           do
-           i=$((i+1))
-           echo "::notice ::Calculating missing dependencies (pass $i)..."
-           pacman -Sy
-           packages=`find /home/build/source/ -name PKGBUILD -exec dirname {} \; | xargs basename -a`
-           missing=$(pacman -Dkk 2>&1 | egrep `echo $packages | sed 's/ /\\|/g'` | cut -f2 -d"'")
+            i=$((i+1))
+            echo "::notice ::Calculating missing dependencies (pass $i)..."
+            packages=`find /home/build/source -name PKGBUILD -exec dirname {} \; | xargs basename -a | tr $'\n' '|'`
+            missing=$(pacman -Dkkq 2>&1 | egrep $packages | cut -f2 -d"'")
 
-           if [ -z "${missing}" ]
-           then
-             echo "::notice ::No missing packages found"
-             break
-           fi
+            if [ -z "${missing}" ]
+            then
+              echo "::notice ::No missing packages found"
+              break
+            fi
 
-           if [ $i -gt 5 ]
-           then
-             echo "::error ::Recursion limit exceeded for adding dependencies!"
-             exit 1
-           fi
+            if [ $i -gt 5 ]
+            then
+              echo "::error ::Recursion limit exceeded for adding dependencies!"
+              exit 1
+            fi
 
-           count=$(echo $missing | tr " " "\n" | wc -l)
-           echo "::notice ::${count} missing packages found"
+            count=$(echo $missing | tr " " "\n" | wc -l)
+            echo "::notice ::${count} missing packages found"
 
-           crema="crema add -r ea-private -n"
-
-           for package in $missing
-           do
-             echo "::group::Building package \"$package\" from AUR"
-             sudo -u build $crema -a $package
-             echo "::endgroup::"
-           done
+            for package in $missing
+            do
+              echo "::group::Building package \"$package\" from AUR"
+              sudo -u build aur sync --noview --noconfirm $package
+              echo "::endgroup::"
+            done
           done
+
+          sleep 600
 
       - name: Clean up build environment
         run: |
-          cp -rv /home/build/ea-private ./out
+          cp -rv /home/build/repo ./out
 
       - name: Import signing key
         uses: crazy-max/ghaction-import-gpg@v4
